### ISSUE TITLE
SLS question

### ISSUE THREAD

**Issue by 947708436** [hopshadoop/hops#770]
is there the new code test about  Scalability  ( the number of machiines )?
i see the SLS code has not changed. the old simulotor can only simulate  5000 nodes  running.

**Comment by berthoug** [comment]
Hi,
We had developed our own version of the SLS (distributedLoadSimulator) at the start of the project in order to evaluate with more than 5000 nodes, but this was not maintained so I can't guaranty it will work. 
The SLS is to evaluate Yarn and our version of yarn is pretty much the same as the apache Hadoop one, so you can refer to their tools.
